library("data.table")
pow_cons<-read.table("household_power_consumption.txt", header=TRUE, sep=";")
pow_cons$datetime<-strptime(paste(pow_cons$Date,pow_cons$Time), "%d/%m/%Y %H:%M:%S")
pow_cons_subset <- subset(pow_cons, datetime > strptime("2007-01-31 23:59:00 EST","%Y-%m-%d %H:%M:%S") & datetime < strptime("2007-02-03 00:00:00 EST","%Y-%m-%d %H:%M:%S"))
pow_cons_subset$Global_active_p <- as.numeric(as.character(pow_cons_subset$Global_active_power))
pow_cons_subset$Global_reactive_p <- as.numeric(as.character(pow_cons_subset$Global_reactive_power))
pow_cons_subset$Sub_metering_1 <- as.numeric(as.character(pow_cons_subset$Sub_metering_1))
pow_cons_subset$Sub_metering_2 <- as.numeric(as.character(pow_cons_subset$Sub_metering_2))
pow_cons_subset$Sub_metering_3 <- as.numeric(as.character(pow_cons_subset$Sub_metering_3))
par(mfrow = c(2,2))
with(pow_cons_subset, plot(datetime,Global_active_p, type="l", xlab="Date",ylab="Global Active Power (kilowatts)"))
with(pow_cons_subset, plot(datetime,Voltage, type="l", xlab="Date",ylab="Voltage"))
with(pow_cons_subset,plot(datetime,Sub_metering_1,type="l",ylab="Energy sub metering"))
with(pow_cons_subset,lines(datetime,Sub_metering_2,col="red"))
with(pow_cons_subset,lines(datetime,Sub_metering_3,col="blue"))
legend("topright", lty=c(1,1), col=c("black","red","blue"), legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
with(pow_cons_subset, plot(datetime,Global_reactive_power, type="l", xlab="Date",ylab="Global Reactive Power"))
dev.copy(png, file = "plot4.png")
dev.off()
